name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: clean compile
        run: mvn --batch-mode --update-snapshots clean compile 
        
      - name: Set up MySQL
        run: | 
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < src/main/sql/create-pscPolideportivo.sql
          mvn --batch-mode --update-snapshots compile 
          mvn --batch-mode --update-snapshots datanucleus:enhance
          mvn --batch-mode --update-snapshots datanucleus:schema-create
          mvn --batch-mode --update-snapshots exec:java -PServer
          
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
                            
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test
        
      - name: Retrieve version
        run: echo "::set-output name=TAG_NAME::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
        id: version

      - uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Github Action genshdoc
        id: action-genshdoc
        uses: vargiuscuola/genshdoc@master
        
      - name: Commit files
        run: |
         echo ${{ github.ref }}
         git add .
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         git commit -m "GitHub Actions CI: Documentacion automatica" -a | exit 0
         
      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
